[GTN_750_1.PANELS]
; display window if true.
visible = true 
; show screen only gauge if true.
nobezel = true 
; display type: WINDOW,PANEL2D,PANEL3D,PANELS
frame.type = PANELS
; display position and dimension (left,top,width,height)
frame.rect = 567,1264,486,517
; screen only border size (pixels).
border.size = 0
; screen only border color (#RGB or #RGBA).
border.rgba = #000000
; enable mouse option: NONE,POPUP,TOUCHSCREEN
usemouse = TOUCHSCREEN[GTN]
; comma separated list of gauges
gauges = GTN_750_1

[GTN_750_1]
; comma separated list of render targets.
drawto = WINDOW, PANEL3D
; is the master device if true.
MasterDevice = true
; connects GPS to copilot side if true.
CopilotSide = false
; selects COM/NAV Radios '1' or '2'.
RadiosPair = 1
; uses computer time if true, simulator time otherwise.
ComputerTime = false
; reduce screen update rate by half.
ReduceRate = false
; integral lighting rheostat index (0 to 3) or percent (-100 to 0)
Rheostat.Display = -100
; integral lighting rheostat index (0 to 3) or percent (-100 to 0)
Rheostat.Buttons = -75
; connects GPS to HSI if true.
LinkHsi = true 
; connects GPS to HSI course if true.
LinkCrs = false
; connects HSI OBS to GPS if true.
LinkObs = false
; connects GPS to VOR if true.
LinkVor = false
; connects GPS to Autopilot if true.
LinkOto = true 
; connects CDI key to NAV/GPS switch if true.
AutoNavGps = true 
; enables automatic GPS/VLOC selection.
AutoSelect = true 
; selects VLOC NAV '1' or '2'. '0' selects same source as 'RadiosPair'.
AutoNavSource = 0
; sets device power source: ALWAYS_ON,AVIONICS_BUS,MAIN_BATTERY
PowerSource = AVIONICS_BUS
; connects GPS to Shadin Air Data computer if true.
UseAirData = true 
; connects GPS to Shadin Fuel Data computer if true.
UseFuelData = true 
; connects GPS to Audio Panel if true.
UseAudioPanel = true 
; connects GPS to Transponder if true.
UseTransponder = true 
; connects GPS to RYAN 9900BX if true.
UseRyanTcad = true 
; sets TCAD sound alerts volume in percent: 0 to 100.
RyanTcadVolume = 50
; enable device failures if true.
UseFailures = false
; intercepts X-Plane GPS commands if true.
UseSimGpsCmds = false
; updates Simulator GPS flight plan if true.
LinkSimGps = false
; saves the active route as a Simulator flight plan if true.
AutoSavePln = false
; sets transponder VFR code (octal default: #1200).
VFRcode = #1200
; sets fuel type: AVGAS,JETA,JETB,DIESEL
FuelType = AVGAS
; sets ownship icon type: 
; AUTO,LOW_WING,HIGH_WING,KIT_PLANE,TURBOPROP,TWIN_ENGINE,SINGLE_JET,BUSINESS_JET,2BLADES,3BLADES,4BLADES,ARROW
OwnshipIcon = LOW_WING
; aviation db: 0: nav_db2_grm, 1: nav_db2, 2: nav_heli_db2_grmn, 3: nav_heli_db2
NavDbType = 1
; sets TAWS type: TERR,TAWS_B,TAWS_A
TawsMode = TAWS_A
; sets TAWS surface: HARD,HARD_SOFT,WATER,ANY
TawsSurface = HARD_SOFT
; TAWS minimum runway length (feet)
TawsMinLength = 40
; TAWS approach air speed (knots), -1 (auto detect Vref: 96)
TawsApprSpeed = 96
; TAWS maximum flap extension speed (knots) or -1 (auto detect Vfe: 125)
TawsFlapSpeed = 125
; TAWS maximum gear extension speed (knots) or -1 (auto detect Vle: 194)
TawsGearSpeed = 194
; sets voice type: MALE,FEMALE
VoicePref = MALE
; sets master sound volume in percent: 0 to 100.
MasterVolume = 100
; mute sound when simulator window looses focus if false.
NoAudioFocus = false
; selects the CPU running the trainer process: 1 to 32
; 0: last core, -1: automatic.
CpuAffinity = -1

[GTN_750_1.WINDOW]
; display window if true.
visible = false
; show screen only gauge if true.
nobezel = false
; display type: WINDOW,PANEL2D,PANEL3D,PANELS
frame.type = WINDOW
; display position and dimension (left,top,width,height)
frame.rect = 567,1264,486,517
; screen only border size (pixels).
border.size = 0
; screen only border color (#RGB or #RGBA).
border.rgba = #000000
; enable mouse clickspots if true, disable if false (use SHIFT to override)
usemouse = true 
; display mouse tooltips if true.
tooltips = false
; freeze display position if true.
locked = false
; left mouse button on the screen toggles popup window if true (requires SHIFT+left mouse button).
popleft = false
; right mouse button on the screen toggles popup window if true (requires XP11.1).
popright = false
; VR mode position and dimension (left,top,width,height) (requires XP11.20)
vrmode.rect = 0,790,830,790
; display as popout window if true (requires XP11.1).
undocked = false

[GTN_750_1.PANEL3D]
; display window if true.
visible = true 
; show screen only gauge if true.
nobezel = true 
; display type: WINDOW,PANEL2D,PANEL3D,PANELS
frame.type = PANEL3D
; display position and dimension (left,top,width,height)
frame.rect = 1014,501,500,379
; screen only border size (pixels).
border.size = 0
; screen only border color (#RGB or #RGBA).
border.rgba = #000000
; enable mouse clickspots if true, disable if false (use SHIFT to override)
usemouse = true
; left mouse button on the screen toggles popup window if true (requires SHIFT+left mouse button).
popleft = true
; right mouse button on the screen toggles popup window if true (requires XP11.1).
popright = false