-- apu_fails.lua
-- Simulates random APU failures and exhaustion of its remaining service life.

-- Only the SmartCopilot master creates or clears failures.
-- Random checks run every 15-30 seconds; condition-driven APU damage is handled separately.

local function defineProps(defs)
    for _, d in ipairs(defs) do
        defineProperty(d[1], d[3](d[2]))
    end
end

-- APU random failure logic.

defineProps({
    -- Global failure level
    { "failures_enabled", "tu154/custom/failures/failures_enabled", globalPropertyi },
    -- Frame time
    { "frame_time", "tu154/custom/time/frame_time", globalPropertyf },
    -- SmartCopilot role: 0 unavailable, 1 slave, 2 master
    { "ismaster", "scp/api/ismaster", globalPropertyf },
    -- Remaining APU service life in seconds
    { "apu_runtime", "tu154/custom/failures/apu_runtime", globalPropertyf },
    -- Starter failure
    { "apu_start_fail", "tu154/custom/failures/apu_start_fail", globalPropertyi },
    -- APU generator failure
    { "apu_gen_fail", "tu154/custom/failures/apu_gen_fail", globalPropertyi },
    -- PTA-6A tachometer converter failure
    { "apu_pta6_fail", "tu154/custom/failures/apu_pta6_fail", globalPropertyi },
    -- Oil-temperature damage flag, generated by apu_logic.lua
    { "apu_fail_oilt", "tu154/custom/failures/apu_fail_oilt", globalPropertyi },
    -- Hot-start / EGT damage flag, generated by apu_logic.lua
    { "apu_fail_egt", "tu154/custom/failures/apu_fail_egt", globalPropertyi },
    -- Residual-fuel start failure, generated by apu_logic.lua
    { "apu_fail_fuel_left", "tu154/custom/failures/apu_fail_fuel_left", globalPropertyi },
    -- General APU failure
    { "apu_fail", "tu154/custom/failures/apu_fail", globalPropertyi },
    -- Bleed-air failure; currently manual/external, not randomly generated here
    { "apu_press_fail", "tu154/custom/failures/apu_press_fail", globalPropertyi },
})

local CHECK_TIME_MIN = 15
local CHECK_TIME_MAX = 30
local RANDOM_FAILURE_BASE = 0.00001 * 0.3
local RUNTIME_FAILURE_BASE = 0.01 * 0.3

local fail_counter = 0
local check_time = math.random(CHECK_TIME_MIN, CHECK_TIME_MAX)

local function failureFactor(level)
    return level * 0.05 * 4 ^ (level * 0.5)
end

local function tryFailure(property, probability)
    if get(property) == 0 and math.random() < probability then
        set(property, 1)
    end
end

local function clearFailure(property)
    if get(property) ~= 0 then
        set(property, 0)
    end
end

local function clearAllFailures()
    clearFailure(apu_start_fail)
    clearFailure(apu_gen_fail)
    clearFailure(apu_pta6_fail)
    clearFailure(apu_fail_oilt)
    clearFailure(apu_fail_egt)
    clearFailure(apu_fail_fuel_left)
    clearFailure(apu_fail)
    clearFailure(apu_press_fail)
end

function update()
    -- SmartCopilot slaves only receive synchronized failure state.
    if get(ismaster) == 1 then
        return
    end

    local passed = get(frame_time)
    if passed <= 0 then
        return
    end

    local failure_level = get(failures_enabled)

    if failure_level <= 0 then
        fail_counter = 0
        clearAllFailures()
        return
    end

    fail_counter = fail_counter + passed
    if fail_counter <= check_time then
        return
    end

    fail_counter = 0
    check_time = math.random(CHECK_TIME_MIN, CHECK_TIME_MAX)

    local fail_factor = failureFactor(failure_level)
    local random_probability = RANDOM_FAILURE_BASE * fail_factor

    -- Preserve the legacy randomly generated failures.
    if failure_level >= 2 then -- LOW retains causal damage only.
        tryFailure(apu_start_fail, random_probability)
        tryFailure(apu_gen_fail, random_probability)
        tryFailure(apu_pta6_fail, random_probability)
        tryFailure(apu_fail, random_probability)
    end

    -- Exhausted service life greatly increases the chance of a general failure.
    if get(apu_runtime) <= 0 then
        tryFailure(apu_fail, RUNTIME_FAILURE_BASE * fail_factor)
    end
end
